name: Run Tests
description: 'Run HiRep tests'
inputs:
  ccache:
    description: "Use ccache"
    required: true
    default: -ccache
  mpi:
    description: "Use mpi"
    required: true
    default: -no-mpi
  nc:
    description: 'Number of colors'
    required: true
  repr:
    description: 'Fermion representation'
    required: true
  ecsw:
    description: "Use ExpCSW"
    required: true
    default: -no-expclover
runs:
  using: 'docker'
  image: 'docker://cpica/hr-tests'
  args:
    - ./TestProgram/run_tests.sh
    - ${{ inputs.ccache }}
    - ${{ inputs.mpi }}
    - ${{ inputs.ecsw }}
    - -n
    - ${{ inputs.nc }}
    - -r
    - ${{ inputs.repr }}
