name: mpi-spn

on:
  push:
    branches:
      - master
      - spn

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      # Ensures that jobs are not cancelled is one job fails
      fail-fast: false
      matrix:
        gaugegroup : [SPN]
        nc: [4, 6]
        repr: [FUND, 2A ]
        ecsw: [-no-clover]
        dir:
        - Algebra
        - DiracOperator
        - Geometry
        - Inverters
        - Mesons
        - PureGauge
        - RIMOM
        - Sources
        - StoredConfs
        - Utils
        - Disconnected
        - GaugeFix
        - Propagator
        - Random
        - Scattering
        - SpinorField
        - Update
        - WilsonLoops
   
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - uses: ./.github/actions/runtests
      with:
        dir: ${{matrix.dir}}
        mpi: -mpi
        nc: ${{ matrix.nc }}
        repr: ${{ matrix.repr }}
        ecsw: ${{ matrix.ecsw }}
        gaugegroup: ${{ matrix.gaugegroup }}
