name: mpi

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      # Ensures that jobs are not cancelled is one job fails
      fail-fast: false
      matrix:
        nc: [2, 3]
        repr: [FUND, ADJ]
        ecsw: [-expclover,-no-expclover]
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - uses: ./.github/actions/runtests
      with:
        mpi: -mpi
        nc: ${{ matrix.nc }}
        repr: ${{ matrix.repr }}
        ecsw: ${{ matrix.ecsw }}
